language: node_js
node_js:
  - "8.11.4"
cache: yarn
branches:
  only:
    - dev
install:
  - yarn global add truffle
  - yarn global add ganache-cli
before_script:
  - ganache-cli >ganache.log 2>&1 &
  - sleep 5
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: dev.kickback.events
  on:
    branch: dev
notifications:
  email:
    - dev-notifications@noblockno.party
