language: node_js
node_js:
  - "8.11.4"
cache: yarn
branches:
  only:
    - dev
script:
  - yarn build
deploy:
  skip_cleanup: true
  provider: surge
  project: ./build/
  domain: dev.noblockno.party
  on:
    branch: dev
notifications:
  email:
    - dev-notifications@noblockno.party
